
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Mar 20 20:47:57 CST 2007
//----------------------------------------------------

package phparser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_AMP = 7;
  public static final int KW_IF = 30;
  public static final int TK_MENOS = 9;
  public static final int TK_STRING = 5;
  public static final int TK_NOTEQ = 24;
  public static final int TK_EQ = 23;
  public static final int TK_IDVAR = 3;
  public static final int KW_PROCEDURE = 25;
  public static final int TK_IGUAL = 18;
  public static final int TK_SLASH = 11;
  public static final int TK_PUNTOCOMA = 12;
  public static final int TK_STAR = 10;
  public static final int TK_ALLAVE = 15;
  public static final int TK_MAS = 8;
  public static final int EOF = 0;
  public static final int KW_WHILE = 31;
  public static final int TK_LT = 21;
  public static final int TK_AND = 20;
  public static final int KW_RETURN = 27;
  public static final int TK_OR = 19;
  public static final int TK_INTEGER = 4;
  public static final int TK_APAREN = 13;
  public static final int TK_CLLAVE = 16;
  public static final int error = 1;
  public static final int TK_FLOAT = 6;
  public static final int TK_COMA = 17;
  public static final int KW_GET = 28;
  public static final int KW_FUNCTION = 26;
  public static final int KW_ELSE = 32;
  public static final int TK_GT = 22;
  public static final int TK_ID = 2;
  public static final int TK_CPAREN = 14;
  public static final int KW_ECHO = 29;
}

