/* The following code was generated by JFlex 1.4.1 on 5/29/07 12:41 PM */

package optimizer;

import java_cup.runtime.*;  // definition of scanner/parser interface
import errormanager.*; // error manager
import IlGen.*;

class TokenValue {          
  public int lineBegin;
  public int charBegin;
  public String text;
  public String filename;   

  TokenValue() {
  }

  TokenValue(String text, int lineBegin, int charBegin, String filename) {
    this.text = new String(text); 
    this.lineBegin = lineBegin; 
    this.charBegin = charBegin;
    this.filename = filename;
     /**Esto solo es para debugear*/
    System.out.println("Linea: " + (lineBegin+1) + ", columna: " + (charBegin+1));
  }

  public String toString() { 
    return text;
  }

  public boolean toBoolean() {
    return Boolean.valueOf(text).booleanValue();  
  }
  
  public int toInt() {
    return Integer.valueOf(text).intValue();
  }

  public double toDouble() {
    return Double.valueOf(text).doubleValue();
  }
  public int getPosLine(){
	return lineBegin;
  }
  public int getPosChar(){
	return charBegin;
  }
}


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 5/29/07 12:41 PM from the specification file
 * <tt>optimizer.l</tt>
 */
public class OptLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int SCANFLINE = 6;
  public static final int STRING = 3;
  public static final int YYINITIAL = 0;
  public static final int CHARACTER = 4;
  public static final int PRINTFLINE = 5;
  public static final int COMMENT2 = 2;
  public static final int COMMENT1 = 1;
  public static final int PREPROC_DIR = 2;

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  7,  0,  6,  8,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     6, 26, 10, 36,  3, 13,  0, 37, 17, 18, 12, 14,  0,  4,  5, 11, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 15, 16, 24, 23, 25,  0, 
     0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 21,  9, 22,  0,  1, 
     0, 35, 38, 34,  1,  1, 32,  1,  1, 29,  1,  1,  1,  1, 30,  1, 
    27,  1, 28, 33, 31,  1,  1,  1,  1,  1,  1, 19,  0, 20,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\5\0\1\2\1\3\1\4\1\2\1\5"+
    "\1\6\1\1\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\2\2\3\1\27\1\30\2\1\2\0"+
    "\1\1\1\31\1\32\1\33\1\0\1\34\1\32\1\35"+
    "\1\36\1\37\1\0\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\2\3\1\0\1\1\1\47\1\1\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\5\3"+
    "\1\60\1\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[78];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\165\0\234\0\303\0\352\0\u0111"+
    "\0\u0138\0\u015f\0\u0186\0\u01ad\0\u01d4\0\u01fb\0\u0111\0\u0222"+
    "\0\u0111\0\u0111\0\u0111\0\u0111\0\u0111\0\u0111\0\u0111\0\u0111"+
    "\0\u0111\0\u0111\0\u0111\0\u0249\0\u0270\0\u0297\0\u02be\0\u02e5"+
    "\0\u030c\0\u0111\0\u0111\0\u0333\0\u035a\0\u0381\0\u03a8\0\u0111"+
    "\0\u03cf\0\u03f6\0\u0111\0\u041d\0\u0111\0\u0111\0\u0111\0\u0444"+
    "\0\u046b\0\u0492\0\u04b9\0\u0111\0\u0111\0\u0111\0\u0111\0\u0111"+
    "\0\u0111\0\u04e0\0\u0507\0\u052e\0\u0555\0\u0111\0\u057c\0\u0111"+
    "\0\u0111\0\u0111\0\u0111\0\u0111\0\u0111\0\u0111\0\u0492\0\u05a3"+
    "\0\u05ca\0\u05f1\0\u0618\0\u063f\0\u0138\0\u0138";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[78];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\10\1\11\1\12\1\13\1\14\1\10\1\15\2\16"+
    "\1\10\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\5\11\1\41\2\11\1\42\1\43"+
    "\1\11\7\44\1\16\1\45\2\44\1\46\1\47\32\44"+
    "\7\50\2\51\36\50\7\52\1\53\1\52\1\54\1\55"+
    "\34\52\7\56\1\53\1\56\1\54\33\56\1\57\1\56"+
    "\7\50\2\60\45\50\2\61\36\50\50\0\2\11\30\0"+
    "\11\11\2\0\1\11\2\0\1\12\2\0\1\62\42\0"+
    "\1\63\31\0\11\63\2\0\1\63\2\0\1\12\52\0"+
    "\1\15\47\0\2\16\51\0\1\64\1\65\61\0\1\66"+
    "\46\0\1\67\46\0\1\70\46\0\1\71\20\0\2\11"+
    "\30\0\1\11\1\72\7\11\2\0\1\11\1\0\2\11"+
    "\30\0\7\11\1\73\1\11\2\0\1\11\7\44\1\0"+
    "\3\44\1\46\1\74\41\44\1\16\1\45\2\44\1\46"+
    "\1\74\41\44\1\0\3\44\1\75\1\0\41\44\1\0"+
    "\3\44\1\76\1\77\32\44\7\0\2\51\36\0\7\52"+
    "\1\0\1\52\2\0\34\52\11\0\1\100\1\101\21\0"+
    "\1\102\1\0\1\103\1\104\5\0\1\105\1\106\7\0"+
    "\2\60\45\0\2\61\40\0\1\107\45\0\2\63\30\0"+
    "\11\63\2\0\1\63\1\0\2\11\30\0\2\11\1\110"+
    "\6\11\2\0\1\11\1\0\2\11\30\0\10\11\1\111"+
    "\2\0\1\11\7\44\1\0\3\44\1\0\1\77\41\44"+
    "\1\0\3\44\1\75\1\74\41\44\1\0\3\44\1\46"+
    "\1\77\32\44\1\0\2\11\30\0\3\11\1\112\5\11"+
    "\2\0\1\11\1\0\2\11\30\0\3\11\1\113\5\11"+
    "\2\0\1\11\1\0\2\11\30\0\4\11\1\114\4\11"+
    "\2\0\1\11\1\0\2\11\30\0\5\11\1\115\3\11"+
    "\2\0\1\11\1\0\2\11\30\0\5\11\1\116\3\11"+
    "\2\0\1\11";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1638];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\5\0\1\11\6\1\1\11\1\1\13\11"+
    "\6\1\2\11\2\1\2\0\1\11\2\1\1\11\1\0"+
    "\3\11\2\1\1\0\1\1\6\11\2\1\1\0\1\1"+
    "\1\11\1\1\7\11\10\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[78];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  public String sourceFilename;
  
  public void init(){};
  public int getLine(){
	return yyline;
	}
public int getChar(){
	return yychar;
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public OptLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public OptLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 41: 
          { Utility.cadenaActual += "\"";
          }
        case 50: break;
        case 49: 
          { // Comentario
		yybegin(PRINTFLINE);
          }
        case 51: break;
        case 36: 
          { return new java_cup.runtime.Symbol(SymOpt.LE, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 52: break;
        case 21: 
          { return new java_cup.runtime.Symbol(SymOpt.LT, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 53: break;
        case 11: 
          { return new java_cup.runtime.Symbol(SymOpt.PLUS, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 54: break;
        case 9: 
          { return new java_cup.runtime.Symbol(SymOpt.ASTERISK, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 55: break;
        case 43: 
          { Utility.cadenaActual += "\n";
          }
        case 56: break;
        case 25: 
          { yybegin(YYINITIAL);   
		yychar = 0;
          }
        case 57: break;
        case 27: 
          { //errorLexico()
		//throw new Exception("Error semantico, no puede haber cambio de linea dentro de una literal de cadena");
          }
        case 58: break;
        case 15: 
          { return new java_cup.runtime.Symbol(SymOpt.CPAR, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 59: break;
        case 40: 
          { Utility.cadenaActual += "\\";
          }
        case 60: break;
        case 35: 
          { return new java_cup.runtime.Symbol(SymOpt.EQ, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 61: break;
        case 10: 
          { return new java_cup.runtime.Symbol(SymOpt.PERCENT, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 62: break;
        case 39: 
          { yybegin(YYINITIAL);
          }
        case 63: break;
        case 28: 
          { yybegin(YYINITIAL);
		return new java_cup.runtime.Symbol(SymOpt.STRING_LITERAL, new TokenValue(Utility.cadenaActual, yyline, yychar, sourceFilename));
          }
        case 64: break;
        case 3: 
          { if (yytext().equals("if"))
		return new java_cup.runtime.Symbol(SymOpt.IF, new TokenValue(yytext(), yyline, yychar, sourceFilename)); 
	if (yytext().equals("goto"))
		return new java_cup.runtime.Symbol(SymOpt.GOTO, new TokenValue(yytext(), yyline, yychar, sourceFilename));
	if (yytext().equals("void"))
		return new java_cup.runtime.Symbol(SymOpt.VOID, new TokenValue(yytext(), yyline, yychar, sourceFilename)); 	 				
	return new java_cup.runtime.Symbol(SymOpt.IDENTIFIER, new TokenValue(new String(yytext()), yyline, yychar, sourceFilename));
          }
        case 65: break;
        case 13: 
          { return new java_cup.runtime.Symbol(SymOpt.SEMICOLON, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 66: break;
        case 31: 
          { yybegin(YYINITIAL);   
		yychar = 0;
		return new java_cup.runtime.Symbol(SymOpt.PRINTF, new TokenValue(new String("scanf" + yytext()), yyline, yychar, sourceFilename));
          }
        case 67: break;
        case 45: 
          { Utility.cadenaActual += "\'";
          }
        case 68: break;
        case 14: 
          { return new java_cup.runtime.Symbol(SymOpt.APAR, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 69: break;
        case 19: 
          { return new java_cup.runtime.Symbol(SymOpt.CCOR, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 70: break;
        case 32: 
          { return new java_cup.runtime.Symbol(SymOpt.IDENTIFIER, new TokenValue(new String(yytext()), yyline, yychar, sourceFilename));
          }
        case 71: break;
        case 26: 
          { Utility.cadenaActual += yytext();
          }
        case 72: break;
        case 29: 
          { yybegin(YYINITIAL);
		return new java_cup.runtime.Symbol(SymOpt.CHAR_LITERAL, new TokenValue(Utility.cadenaActual, yyline, yychar, sourceFilename));
          }
        case 73: break;
        case 44: 
          { Utility.cadenaActual += "\t";
          }
        case 74: break;
        case 5: 
          { return new java_cup.runtime.Symbol(SymOpt.MINUS, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 75: break;
        case 6: 
          { yychar++;
          }
        case 76: break;
        case 46: 
          { Utility.cadenaActual += "\b";
          }
        case 77: break;
        case 16: 
          { return new java_cup.runtime.Symbol(SymOpt.ALLAVE, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 78: break;
        case 24: 
          { Utility.cadenaActual = "";
		yybegin(CHARACTER);
          }
        case 79: break;
        case 18: 
          { return new java_cup.runtime.Symbol(SymOpt.ACOR, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 80: break;
        case 8: 
          { return new java_cup.runtime.Symbol(SymOpt.SLASH, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 81: break;
        case 1: 
          { yychar = 0;
          }
        case 82: break;
        case 37: 
          { return new java_cup.runtime.Symbol(SymOpt.GE, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 83: break;
        case 22: 
          { return new java_cup.runtime.Symbol(SymOpt.GT, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 84: break;
        case 23: 
          { // Comentario
		yybegin(PREPROC_DIR);
          }
        case 85: break;
        case 4: 
          { return new java_cup.runtime.Symbol(SymOpt.INTEGER_LITERAL, new TokenValue(new String(yytext()), yyline, yychar, sourceFilename));
          }
        case 86: break;
        case 42: 
          { Utility.cadenaActual += "\r";
          }
        case 87: break;
        case 30: 
          { yybegin(YYINITIAL);   
		yychar = 0;
		return new java_cup.runtime.Symbol(SymOpt.PRINTF, new TokenValue(new String("printf" + yytext()), yyline, yychar, sourceFilename));
          }
        case 88: break;
        case 20: 
          { return new java_cup.runtime.Symbol(SymOpt.EQUALS, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 89: break;
        case 48: 
          { // Comentario
		yybegin(SCANFLINE);
          }
        case 90: break;
        case 2: 
          { ErrorManager.agregarErrorLexico(yyline,yychar, "Error lexico: Simbolo " + yytext() + " Invalido");
		System.out.println("Error lexico: Simbolo " + yytext() + " Invalido en " + yyline + ", " +yychar +".");
          }
        case 91: break;
        case 12: 
          { return new java_cup.runtime.Symbol(SymOpt.COLON, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 92: break;
        case 38: 
          { return new java_cup.runtime.Symbol(SymOpt.NE, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 93: break;
        case 17: 
          { return new java_cup.runtime.Symbol(SymOpt.CLLAVE, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 94: break;
        case 33: 
          { // Comentario
		yybegin(COMMENT2);
          }
        case 95: break;
        case 7: 
          { Utility.cadenaActual = "";
		yybegin(STRING);
          }
        case 96: break;
        case 47: 
          { return new java_cup.runtime.Symbol(SymOpt.FLOATING_LITERAL, new TokenValue(new String(yytext()), yyline, yychar, sourceFilename));
          }
        case 97: break;
        case 34: 
          { // Comentario
		yybegin(COMMENT1);
          }
        case 98: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {   return new java_cup.runtime.Symbol(SymOpt.EOF, new TokenValue(yytext(), yyline, yychar, sourceFilename));
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
