first : first.cpp
	g++ -ggdb -Wall -o first first.cpp
firstlinuxrelease : first.cpp
	g++ $(CFLAGS) -Wall -o first first.cpp
firstwin32release: first.cpp
	g++ $(CFLAGS) -Wall -o first.exe first.cpp
clean:
	rm -f *.o first



