/* The following code was generated by JFlex 1.4.1 on 5/29/07 7:19 PM */

package ui;

import java_cup.runtime.*;  // definition of scanner/parser interface
//import IlGen.TokenValue;

/* semantic value of token returned by scanner */
class TokenValue {          
  public int lineBegin;
  public int charBegin;
  public String text;
  public String filename;   

  TokenValue() {
  }

  TokenValue(String text, int lineBegin, int charBegin, String filename) {
    this.text = new String(text); 
    this.lineBegin = lineBegin; 
    this.charBegin = charBegin;
    this.filename = filename;
     /**Esto solo es para debugear*/
    System.out.println("Linea: " + (lineBegin+1) + ", columna: " + (charBegin+1));
  }

  public String toString() { 
    return text;
  }

  public boolean toBoolean() {
    return Boolean.valueOf(text).booleanValue();  
  }
  
  public int toInt() {
    return Integer.valueOf(text).intValue();
  }

  public double toDouble() {
    return Double.valueOf(text).doubleValue();
  }
  public int getPosLine(){
	return lineBegin;
  }
  public int getPosChar(){
	return charBegin;
  }
}




/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 5/29/07 7:19 PM from the specification file
 * <tt>ConsoleLexer.l</tt>
 */
public class ConsoleLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 1;
  public static final int YYINITIAL = 0;
  public static final int CHARACTER = 1;
  public static final int COMMENT2 = 1;
  public static final int COMMENT1 = 1;
  public static final int PREPROC_DIR = 1;

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  4,  0,  3,  4,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     7,  0,  0,  2,  0,  0,  0,  0,  2,  2,  0,  0,  0, 26, 25,  8, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  6,  2,  2,  2,  2,  2, 
    21, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 
    28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,  0,  5,  0,  0,  1, 
     0, 28, 28,  9, 10, 11, 28, 28, 22, 13, 28, 28, 15, 23, 19, 16, 
    27, 28, 18, 17, 14, 28, 24, 20, 12, 28, 28,  2,  0,  2,  2,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\1\2\1\3\1\4\6\1\1\5\3\1"+
    "\1\0\1\4\1\1\1\6\2\1\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\1\1\15\1\1\1\16\1\17"+
    "\1\20\1\21\4\1\1\22\1\23\1\24\2\1\1\25"+
    "\1\26\1\27\1\1\1\30";

  private static int [] zzUnpackAction() {
    int [] result = new int[50];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\35\0\35\0\72\0\127\0\164\0\221\0\256"+
    "\0\313\0\350\0\u0105\0\u0122\0\u013f\0\35\0\u015c\0\u0179"+
    "\0\u0196\0\u01b3\0\u01d0\0\u01ed\0\u01ed\0\u020a\0\u0227\0\u01ed"+
    "\0\u01ed\0\u01ed\0\u01ed\0\u01ed\0\u01ed\0\u0244\0\u01ed\0\u0261"+
    "\0\u027e\0\35\0\u029b\0\35\0\u02b8\0\u02d5\0\u02f2\0\u030f"+
    "\0\u01ed\0\u01ed\0\35\0\u032c\0\u0349\0\u01ed\0\u01ed\0\u01ed"+
    "\0\u0366\0\u01ed";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[50];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\3\1\5\1\6\1\7\1\3\1\5"+
    "\1\7\1\10\1\11\1\12\3\11\1\13\1\11\1\14"+
    "\1\11\1\15\1\11\1\16\1\11\1\17\1\11\1\20"+
    "\1\21\2\11\43\0\1\22\31\0\1\5\3\0\1\5"+
    "\31\0\1\6\31\0\2\23\3\0\17\23\1\0\4\23"+
    "\1\0\2\23\6\0\1\22\2\0\1\24\1\25\4\24"+
    "\1\26\5\24\1\0\3\24\2\0\2\24\6\0\1\22"+
    "\2\0\14\24\1\0\3\24\2\0\2\24\6\0\1\22"+
    "\2\0\3\24\1\27\10\24\1\0\3\24\2\0\2\24"+
    "\6\0\1\22\2\0\3\24\1\30\10\24\1\0\3\24"+
    "\2\0\2\24\6\0\1\22\2\0\2\24\1\31\1\32"+
    "\1\33\1\34\3\24\1\35\2\24\1\0\1\36\2\24"+
    "\2\0\1\37\1\24\6\0\1\22\2\0\2\24\1\40"+
    "\11\24\1\0\3\24\2\0\2\24\6\0\1\22\2\0"+
    "\14\24\1\0\2\24\1\41\2\0\2\24\31\0\1\42"+
    "\24\0\1\43\4\0\1\44\13\0\1\7\2\0\1\7"+
    "\25\0\2\23\2\0\1\7\17\23\1\0\4\23\1\0"+
    "\2\23\11\0\14\24\1\0\3\24\2\0\2\24\11\0"+
    "\7\24\1\45\1\24\1\46\2\24\1\0\3\24\2\0"+
    "\2\24\11\0\4\24\1\47\7\24\1\0\3\24\2\0"+
    "\2\24\11\0\7\24\1\50\4\24\1\0\3\24\2\0"+
    "\2\24\11\0\13\24\1\51\1\0\3\24\2\0\2\24"+
    "\11\0\1\52\13\24\1\0\3\24\2\0\2\24\20\0"+
    "\1\53\25\0\10\24\1\54\3\24\1\0\3\24\2\0"+
    "\2\24\11\0\10\24\1\55\3\24\1\0\3\24\2\0"+
    "\2\24\11\0\5\24\1\56\6\24\1\0\3\24\2\0"+
    "\2\24\11\0\13\24\1\57\1\0\3\24\2\0\2\24"+
    "\11\0\2\24\1\60\11\24\1\0\3\24\2\0\2\24"+
    "\11\0\1\61\13\24\1\0\3\24\2\0\2\24\11\0"+
    "\11\24\1\62\2\24\1\0\3\24\2\0\2\24";

  private static int [] zzUnpackTrans() {
    int [] result = new int[899];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\10\1\11\12\1\1\11\3\1\1\0\17\1"+
    "\1\11\1\1\1\11\6\1\1\11\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[50];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  public String sourceFilename;
  
  public void init(){};
  public int getLine(){
	return yyline;
	}
public int getChar(){
	return yychar;
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ConsoleLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public ConsoleLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 3: 
          { yychar = 0;
          }
        case 25: break;
        case 1: 
          { MainWindow.getConsolaActual().writeLn("Error: Simbolo " + yytext() + " Invalido en " + yyline + ", " +yychar +", verifique que no este en mayusculas y que sea un comando valido.");
          }
        case 26: break;
        case 17: 
          { return new java_cup.runtime.Symbol(SymConsole.HELP, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 27: break;
        case 9: 
          { return new java_cup.runtime.Symbol(SymConsole.SX, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 28: break;
        case 24: 
          { return new java_cup.runtime.Symbol(SymConsole.CLEAR, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 29: break;
        case 6: 
          { return new java_cup.runtime.Symbol(SymConsole.CD, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 30: break;
        case 11: 
          { return new java_cup.runtime.Symbol(SymConsole.ST, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 31: break;
        case 4: 
          { return new java_cup.runtime.Symbol(SymConsole.FILENAME, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 32: break;
        case 13: 
          { return new java_cup.runtime.Symbol(SymConsole.SP, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 33: break;
        case 2: 
          { yychar++;
          }
        case 34: break;
        case 18: 
          { return new java_cup.runtime.Symbol(SymConsole.NEW, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 35: break;
        case 10: 
          { return new java_cup.runtime.Symbol(SymConsole.SI, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 36: break;
        case 5: 
          { return new java_cup.runtime.Symbol(SymConsole.ARROBA, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 37: break;
        case 22: 
          { return new java_cup.runtime.Symbol(SymConsole.SHOW, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 38: break;
        case 7: 
          { return new java_cup.runtime.Symbol(SymConsole.LX, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 39: break;
        case 14: 
          { return new java_cup.runtime.Symbol(SymConsole.MV, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 40: break;
        case 15: 
          { return new java_cup.runtime.Symbol(SymConsole.DOTDOT, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 41: break;
        case 21: 
          { return new java_cup.runtime.Symbol(SymConsole.EXIT, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 42: break;
        case 16: 
          { return new java_cup.runtime.Symbol(SymConsole.SS, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 43: break;
        case 19: 
          { return new java_cup.runtime.Symbol(SymConsole.MVC, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 44: break;
        case 8: 
          { return new java_cup.runtime.Symbol(SymConsole.SE, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 45: break;
        case 12: 
          { return new java_cup.runtime.Symbol(SymConsole.SR, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 46: break;
        case 23: 
          { return new java_cup.runtime.Symbol(SymConsole.CLOSE, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 47: break;
        case 20: 
          { return new java_cup.runtime.Symbol(SymConsole.SO, new TokenValue(yytext(), yyline, yychar, sourceFilename));
          }
        case 48: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {   return new java_cup.runtime.Symbol(SymConsole.EOF, new TokenValue(yytext(), yyline, yychar, sourceFilename));
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
