
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue May 29 19:19:22 CST 2007
//----------------------------------------------------

package ui;

/** CUP generated class containing symbol constants. */
public class SymConsole {
  /* terminals */
  public static final int EXIT = 3;
  public static final int HELP = 14;
  public static final int CLOSE = 4;
  public static final int CLEAR = 5;
  public static final int FILE = 12;
  public static final int SHOW = 8;
  public static final int CD = 2;
  public static final int SX = 22;
  public static final int MV = 10;
  public static final int MVC = 9;
  public static final int ST = 18;
  public static final int SS = 20;
  public static final int SR = 16;
  public static final int SP = 17;
  public static final int SO = 15;
  public static final int EOF = 0;
  public static final int DOTDOT = 13;
  public static final int SI = 19;
  public static final int error = 1;
  public static final int SE = 23;
  public static final int FILENAME = 11;
  public static final int NEW = 6;
  public static final int ARROBA = 7;
  public static final int LX = 21;
}

