
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue May 29 22:02:27 CST 2007
//----------------------------------------------------

package IlGen;

/** CUP generated class containing symbol constants. */
public class SymCpp {
  /* terminals */
  public static final int IDENTIFIER = 37;
  public static final int BOOL = 25;
  public static final int GT = 87;
  public static final int ARROW = 79;
  public static final int SCANF = 32;
  public static final int CONST = 29;
  public static final int ASS_AND = 62;
  public static final int NOTBIN = 73;
  public static final int GE = 50;
  public static final int ASS_XOR = 63;
  public static final int REGISTER = 19;
  public static final int SIZEOF = 2;
  public static final int FLOATING_LITERAL = 41;
  public static final int VIRTUAL = 23;
  public static final int ARROW_STAR = 77;
  public static final int APAR = 81;
  public static final int LT = 86;
  public static final int STRUCT = 35;
  public static final int CPAR = 82;
  public static final int SHR = 48;
  public static final int SCOPE = 78;
  public static final int PROTECTED = 21;
  public static final int INTEGER_LITERAL = 39;
  public static final int FALSE = 42;
  public static final int LE = 49;
  public static final int SHL = 47;
  public static final int DEC = 46;
  public static final int INLINE = 24;
  public static final int FLOAT = 28;
  public static final int ACOR = 83;
  public static final int EQ = 51;
  public static final int CCOR = 84;
  public static final int ASS_SUB = 59;
  public static final int CLASS = 34;
  public static final int ASS_SHR = 61;
  public static final int COMA = 66;
  public static final int SLASH = 75;
  public static final int PRINTF = 33;
  public static final int ASS_SHL = 60;
  public static final int DOT_STAR = 76;
  public static final int TRUE = 43;
  public static final int PLUS = 71;
  public static final int PERCENT = 85;
  public static final int WHILE = 9;
  public static final int UNION = 36;
  public static final int DELETE = 53;
  public static final int ASS_OR = 64;
  public static final int ALLAVE = 94;
  public static final int CHAR = 26;
  public static final int ASS_MUL = 55;
  public static final int SWITCH = 8;
  public static final int DO = 10;
  public static final int ASS_MOD = 57;
  public static final int FOR = 11;
  public static final int LOG_OR = 70;
  public static final int VOID = 31;
  public static final int EXTERN = 16;
  public static final int PUBLIC = 20;
  public static final int RETURN = 14;
  public static final int ELSE = 7;
  public static final int ASTERISK = 68;
  public static final int BREAK = 13;
  public static final int AMPERSAND = 67;
  public static final int INT = 27;
  public static final int NULL_LITERAL = 44;
  public static final int STRING_LITERAL = 38;
  public static final int SEMICOLON = 93;
  public static final int EOF = 0;
  public static final int PUNTO = 65;
  public static final int THIS = 3;
  public static final int DEFAULT = 5;
  public static final int REDUCE_HERE_MOSTLY = 97;
  public static final int INC = 45;
  public static final int ASS_ADD = 58;
  public static final int ASS_DIV = 56;
  public static final int MINUS = 72;
  public static final int error = 1;
  public static final int SHIFT_THERE = 96;
  public static final int CONTINUE = 12;
  public static final int IF = 6;
  public static final int COLON = 91;
  public static final int LOG_AND = 69;
  public static final int CLLAVE = 95;
  public static final int CARET = 88;
  public static final int NOTLOG = 74;
  public static final int VOLATILE = 30;
  public static final int CHAR_LITERAL = 40;
  public static final int QUEST = 90;
  public static final int CASE = 4;
  public static final int NEW = 54;
  public static final int BAR = 89;
  public static final int PRIVATE = 22;
  public static final int ELLIPSIS = 80;
  public static final int STATIC = 17;
  public static final int NE = 52;
  public static final int TYPEDEF = 15;
  public static final int EQUALS = 92;
  public static final int AUTO = 18;
}

