
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue May 08 23:28:32 CST 2007
//----------------------------------------------------

package IlGen;

/** CUP generated class containing symbol constants. */
public class SymJava {
  /* terminals */
  public static final int IDENTIFIER = 9;
  public static final int ANDEQ = 73;
  public static final int GT = 54;
  public static final int CONST = 82;
  public static final int NOTEQ = 58;
  public static final int PLUSEQ = 68;
  public static final int RBRACK = 8;
  public static final int COMMA = 13;
  public static final int RBRACE = 15;
  public static final int RPAREN = 18;
  public static final int LBRACK = 7;
  public static final int LT = 53;
  public static final int ANDAND = 62;
  public static final int OROR = 63;
  public static final int LBRACE = 14;
  public static final int LPAREN = 17;
  public static final int XOREQ = 74;
  public static final int PROTECTED = 23;
  public static final int INTEGER_LITERAL = 76;
  public static final int NOT = 48;
  public static final int FINAL = 27;
  public static final int FLOAT = 5;
  public static final int GOTO = 83;
  public static final int URSHIFTEQ = 72;
  public static final int PACKAGE = 20;
  public static final int COMP = 47;
  public static final int EQ = 16;
  public static final int BOOLEAN_LITERAL = 78;
  public static final int MOD = 50;
  public static final int CLASS = 28;
  public static final int ABSTRACT = 26;
  public static final int PLUS = 45;
  public static final int QUESTION = 64;
  public static final int WHILE = 37;
  public static final int CHAR = 4;
  public static final int BOOLEAN = 2;
  public static final int SWITCH = 33;
  public static final int DO = 36;
  public static final int FOR = 38;
  public static final int RSHIFTEQ = 71;
  public static final int VOID = 29;
  public static final int DIV = 49;
  public static final int PUBLIC = 22;
  public static final int RETURN = 41;
  public static final int MULT = 12;
  public static final int ELSE = 32;
  public static final int BREAK = 39;
  public static final int GTEQ = 56;
  public static final int DOT = 10;
  public static final int INT = 3;
  public static final int NULL_LITERAL = 81;
  public static final int STRING_LITERAL = 80;
  public static final int EQEQ = 57;
  public static final int EOF = 0;
  public static final int SEMICOLON = 11;
  public static final int THIS = 30;
  public static final int DEFAULT = 35;
  public static final int MULTEQ = 65;
  public static final int IMPORT = 21;
  public static final int MINUS = 46;
  public static final int LTEQ = 55;
  public static final int OR = 61;
  public static final int error = 1;
  public static final int DIVEQ = 66;
  public static final int LSHIFTEQ = 70;
  public static final int CONTINUE = 40;
  public static final int IF = 31;
  public static final int MODEQ = 67;
  public static final int MINUSMINUS = 44;
  public static final int COLON = 19;
  public static final int CHARACTER_LITERAL = 79;
  public static final int OREQ = 75;
  public static final int CASE = 34;
  public static final int PLUSPLUS = 43;
  public static final int NEW = 42;
  public static final int RSHIFT = 52;
  public static final int STRING = 6;
  public static final int AND = 59;
  public static final int PRIVATE = 24;
  public static final int ELLIPSIS = 84;
  public static final int STATIC = 25;
  public static final int LSHIFT = 51;
  public static final int XOR = 60;
  public static final int FLOATING_POINT_LITERAL = 77;
  public static final int MINUSEQ = 69;
}

