
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue May 29 21:39:38 CST 2007
//----------------------------------------------------

package IlGen;

/** CUP generated class containing symbol constants. */
public class SymPascal {
  /* terminals */
  public static final int IDENTIFIER = 27;
  public static final int CHARACTER_STRING = 6;
  public static final int REAL = 72;
  public static final int GT = 26;
  public static final int PACKED = 43;
  public static final int TYPE = 61;
  public static final int STARSTAR = 58;
  public static final int READ = 69;
  public static final int CONST = 9;
  public static final int GE = 24;
  public static final int UNTIL = 62;
  public static final int ASSIGNMENT = 4;
  public static final int COMMA = 8;
  public static final int RPAREN = 53;
  public static final int LT = 34;
  public static final int INTEGER = 71;
  public static final int LPAREN = 33;
  public static final int NOT = 38;
  public static final int LE = 32;
  public static final int NIL = 37;
  public static final int ARRAY = 3;
  public static final int VAR = 64;
  public static final int THEN = 59;
  public static final int GOTO = 25;
  public static final int PBEGIN = 44;
  public static final int UPARROW = 63;
  public static final int EXTERNAL = 20;
  public static final int RECORD = 51;
  public static final int MOD = 36;
  public static final int SLASH = 56;
  public static final int WRITE = 67;
  public static final int PLUS = 46;
  public static final int WHILE = 65;
  public static final int EQUAL = 19;
  public static final int CHAR = 74;
  public static final int DO = 13;
  public static final int DIGSEQ = 10;
  public static final int FOR = 21;
  public static final int STAR = 57;
  public static final int DIV = 12;
  public static final int DOWNTO = 16;
  public static final int READLN = 70;
  public static final int ELSE = 17;
  public static final int DOTDOT = 15;
  public static final int DOT = 14;
  public static final int PROCEDURE = 47;
  public static final int EOF = 0;
  public static final int SEMICOLON = 54;
  public static final int FUNCTION = 23;
  public static final int REPEAT = 52;
  public static final int LABEL = 30;
  public static final int MINUS = 35;
  public static final int IN = 29;
  public static final int OR = 41;
  public static final int SET = 55;
  public static final int error = 1;
  public static final int WRITELN = 68;
  public static final int PFILE = 45;
  public static final int IF = 28;
  public static final int RBRAC = 49;
  public static final int OF = 40;
  public static final int END = 18;
  public static final int COLON = 7;
  public static final int OTHERWISE = 42;
  public static final int NOTEQUAL = 39;
  public static final int CASE = 5;
  public static final int FORWARD = 22;
  public static final int STRING = 73;
  public static final int LBRAC = 31;
  public static final int PROGRAM = 48;
  public static final int AND = 2;
  public static final int TO = 60;
  public static final int REALNUMBER = 50;
  public static final int WITH = 66;
  public static final int USES = 11;
}

