/**CONSULTA 1*/
/*
DAR EL CARNET, NOMBRE, CARRERA, PLAN, PROMEDIO DE NOTAS Y NUMERO DE CREDITOS APROBADOS DE TODOS LOS ESTUDIANTES QUE HAN CERRADO ALGUNA CARRERA

OBTENER ESTUDIANTE TAL QUE EN CADA CARRERA TAL QUE EN EL PENSUM DE ESA CARRERA NO EXISTA NINGUN CURSO OBLIGATORIO QUE NO EXISTA COMO CURSO GANADO EN LAS ASIGNACIONES Y EXISTA UNA SUMA DE CREDITOS > 250 */
SELECT E.CARNET, E.PRIMER_NOMBRE || ' ' || E.PRIMER_APELLIDO
FROM ESTUDIANTE E, CARRERA C, PLAN PL, ESTUDIANTE_CARR_PROM_EDAD ECPE
WHERE ECPE.CARNET = E.CARNET
AND ECPE.CARRERA = C.CARRERA
AND EXISTS(
	SELECT 1
	FROM CARRERA CA1	
	WHERE CA1.CARRERA = C.CARRERA
	AND EXISTS (
		SELECT 1
		FROM PENSUM PE1		
		WHERE PE1.CARRERA = CA1.CARRERA
		AND OBLIGATORIO = 1
		AND NOT EXISTS(
			SELECT 1
			FROM CURSO CU1
			WHERE CU1.CURSO = PE1.CODIGO
			AND NOT EXISTS(
				SELECT 1
				FROM ASIGNACION AS1, APROBACION AP1, PLAN PL1
				WHERE AS1.CODIGO = CU1.CURSO
				AND AS1.CARNET = E.CARNET
				AND ((PL1.ANIO_INICIO = AS1.ANIO AND PL1.CICLO_INICIO <= AS1.CICLO)
						OR (PL1.ANIO_FIN = AS1.ANIO AND PL1.CICLO_FIN >= AS1.CICLO)
						OR (PL1.ANIO_INICIO < AS1.ANIO AND PL1.ANIO_FIN > AS1.ANIO)
				)
				AND PE1.PLAN = PL1.PLAN
				AND PE1.CARRERA = PL1.CARRERA
				AND AP1.PLAN = PL1.PLAN
				AND AP1.CARRERA = PL1.CARRERA
				AND AP1.CICLO = AS1.CICLO
				AND AS1.NOTA >= AP1.NOTA_APROBACION
				AND AS1.ZONA >= AP1.ZONA_MINIMA
				AND PL.PLAN = PL1.PLAN
			)
		)
	)
	AND EXISTS(
		SELECT 1
		FROM PENSUM PE1		
		WHERE PE1.CARRERA = CA1.CARRERA
		AND NOT EXISTS(
			SELECT SUM(CREDITOS)
			FROM CURSO CU1
			WHERE CU1.CURSO = PE1.CODIGO
			AND NOT EXISTS(
				SELECT 1
				FROM ASIGNACION AS1, APROBACION AP1, PLAN PL1
				WHERE AS1.CODIGO = CU1.CURSO
				AND AS1.CARNET = E.CARNET
				AND ((PL1.ANIO_INICIO = AS1.ANIO AND PL1.CICLO_INICIO <= AS1.CICLO)
						OR (PL1.ANIO_FIN = AS1.ANIO AND PL1.CICLO_FIN >= AS1.CICLO)
						OR (PL1.ANIO_INICIO < AS1.ANIO AND PL1.ANIO_FIN > AS1.ANIO)
				)
				AND PE1.PLAN = PL1.PLAN
				AND PE1.CARRERA = PL1.CARRERA
				AND AP1.PLAN = PL1.PLAN
				AND AP1.CARRERA = PL1.CARRERA
				AND AP1.CICLO = AS1.CICLO
				AND AS1.NOTA >= AP1.NOTA_APROBACION
				AND AS1.ZONA >= AP1.ZONA_MINIMA
			)
			HAVING SUM(CREDITOS) > CA1.CREDITOS_CIERRE 
		)
	)	
);



