/**CONSULTA 5*/
/*
DAR LOS DATOS GENERALES DE LOS ESTUDIANTES QUE HABIENDOSE ASIGNADO EXACTAMENTE LOS MISMOS CURSOS EN LA MISMA SECCION, SIEMPRE HAN APROBADO O REPROBADO A LA VEZ CADA CURSO.

Obtenemos una pareja de estudiantes que esten asignados en la misma seccion y que hayan aprobado o reprobado el mismo curso asignado el mismo ciclo
*/
SELECT DISTINCT E1.CARNET, E2.CARNET
FROM ESTUDIANTE E1, ESTUDIANTE E2, ASIGNACION A1, ASIGNACION A2, APROBACION AP1, APROBACION AP2, PLAN PL1, PLAN PL2
WHERE E1.CARNET = A1.CARNET
AND E2.CARNET = A2.CARNET
AND A1.SECCION = A2.SECCION
AND A1.CODIGO = A2.CODIGO
AND PL1.CARRERA = E1.CARRERA
AND ((PL1.ANIO_INICIO = A1.ANIO AND PL1.CICLO_INICIO <= A1.CICLO)
	OR (PL1.ANIO_FIN = A1.ANIO AND PL1.CICLO_FIN >= A1.CICLO)
	OR (PL1.ANIO_INICIO < A1.ANIO AND PL1.ANIO_FIN > A1.ANIO)
)
AND PL2.CARRERA = E2.CARRERA
AND ((PL2.ANIO_INICIO = A2.ANIO AND PL2.CICLO_INICIO <= A2.CICLO)
	OR (PL2.ANIO_FIN = A2.ANIO AND PL2.CICLO_FIN >= A2.CICLO)
	OR (PL2.ANIO_INICIO < A2.ANIO AND PL2.ANIO_FIN > A2.ANIO)
)
AND AP1.PLAN = PL1.PLAN
AND AP1.CARRERA = PL1.CARRERA
AND AP1.CICLO = A1.CICLO
AND AP2.PLAN = PL2.PLAN
AND AP2.CARRERA = PL2.CARRERA
AND AP2.CICLO = A2.CICLO
AND (   (
	A1.NOTA < AP1.NOTA_APROBACION
	AND A1.ZONA < AP1.ZONA_MINIMA
	AND A2.NOTA < AP2.NOTA_APROBACION
	AND A2.NOTA < AP2.ZONA_MINIMA
	) OR (
	A1.NOTA >= AP1.NOTA_APROBACION
	AND A1.ZONA >= AP1.ZONA_MINIMA
	AND A2.NOTA >= AP2.NOTA_APROBACION
	AND A2.NOTA >= AP2.ZONA_MINIMA
	)
);


