/**CONSULTA 6*/
/*
DAR LA LISTA DE CURSOS PARA AQUELLLOS CURSOSQUE EN EL PRESENTE PLAN TIENEN MAS CURSOS PERREQUISITO QUE POSTREQUISITO

Obtenemos todos los cursos tal que sus prerrequisitos sean mas que sus postrequisitos utilizando tablas como select anidados
*/
SELECT DISTINCT CU1.*, POSTPRE, POSTCOD"Cursos Postrrequisito", PREPRE"Cursos Prerrequisito"
FROM CURSO CU1, ( 
	SELECT  P4.CARRERA"POSTCAR", P4.PLAN "POSTPLAN", P4.PRERREQUISITO"POSTPRE", COUNT(DISTINCT P4.CODIGO)"POSTCOD"
	FROM PRERREQUISITO P4
	GROUP BY P4.CARRERA, P4.PLAN, P4.PRERREQUISITO
	) , ( 
	SELECT  P5.CARRERA"PRECAR", P5.PLAN "PREPLAN", P5.CODIGO"PRECOD", COUNT(DISTINCT P5.PRERREQUISITO)"PREPRE"
	FROM PRERREQUISITO P5
	GROUP BY P5.CARRERA, P5.PLAN, P5.CODIGO
	) , PLAN PL1
WHERE
	PL1.PLAN = POSTPLAN
	AND PL1.CARRERA = POSTCAR
	AND PL1.PLAN = PREPLAN
	AND PL1.CARRERA = PRECAR
	AND PL1.ANIO_FIN >= 2007
	AND PL1.CICLO_FIN >= 1
	AND CU1.CURSO = POSTPRE
	AND CU1.CURSO = PRECOD
	AND POSTCOD < PREPRE
;




