/**CONSULTA 19*/
/*
Listado de curso/catedratico/auxiliar donde los alumnos tengan mejor nota promedio que otra seccion del mismo anio y ciclo anterior tal que no haya sido el mismo catedratico

Obtenemos el curso, catedratico, auxiliar, y promocion tal que en un par de secciones dadas por diferente catedratico exista mejor promedio, se uso vista PROM_POR_CUR_SEC_ANIO_CICLO.
*/
SELECT DISTINCT SEC1.CODIGO,CAT1.NOMBRE,AUX1.AUXILIAR,P1.PROM,P2.PROM
FROM SECCION SEC1, SECCION SEC2, CATEDRATICO CAT1, CATEDRATICO CAT2, AUXILIAR AUX1, AUXILIAR AUX2,PROM_POR_CUR_SEC_ANIO_CICLO P1, PROM_POR_CUR_SEC_ANIO_CICLO P2
WHERE P1.SECCION = SEC1.SECCION
AND P1.CICLO = SEC1.CICLO
AND P1.CURSO = SEC1.CODIGO
AND P2.SECCION = SEC2.SECCION
AND P2.CICLO = SEC2.CICLO
AND P2.CURSO = SEC2.CODIGO
AND SEC1.AUXILIAR = AUX1.AUXILIAR
AND SEC2.AUXILIAR = AUX2.AUXILIAR
AND SEC1.CATEDRATICO = CAT1.CATEDRATICO
AND SEC2.CATEDRATICO = CAT2.CATEDRATICO
AND SEC1.CATEDRATICO <> SEC2.CATEDRATICO
AND SEC1.AUXILIAR <> SEC2.AUXILIAR
AND P1.PROM > P2.PROM
;





