/**CONSULTA 23*/
/*
Normalizar las notas de todos los cursos asumiendo que la nueva nota minima de aprobacion sera de 75 independientemente del ciclo en que se eaprobo el curso.

Actualiza utilizando formula AS1.NOTA +(75-(nota_aprobacion actual))) todas las notas ganadas de cualquier asignacion dada
*/
UPDATE ASIGNACION AS1
	SET AS1.NOTA = AS1.NOTA +(75-(
		SELECT UNIQUE AP1.NOTA_APROBACION"NOTA_APROBRACION"
		FROM APROBACION AP1, PLAN PL1, ESTUDIANTE E1
		WHERE E1.CARNET = AS1.CARNET
		AND (	(PL1.ANIO_INICIO = AS1.ANIO AND PL1.CICLO_INICIO <= AS1.CICLO)
			OR (PL1.ANIO_FIN = AS1.ANIO AND PL1.CICLO_FIN >= AS1.CICLO)
			OR (PL1.ANIO_INICIO < AS1.ANIO AND PL1.ANIO_FIN > AS1.ANIO)
		)
		/*
		AND PL1.ANIO_INICIO <= AS1.ANIO
		AND PL1.ANIO_FIN > AS1.ANIO
		AND PL1.CICLO_INICIO <= AS1.CICLO
		AND PL1.CICLO_FIN > AS1.CICLO*/
		AND PL1.CARRERA = E1.CARRERA
		AND AP1.PLAN = PL1.PLAN
		AND AP1.CARRERA = PL1.CARRERA
		AND AP1.CICLO = AS1.CICLO
		))
	WHERE
	AS1.NOTA < 100 - (75 - 
		(
		SELECT UNIQUE AP1.NOTA_APROBACION"NOTA_APROBRACION"
		FROM APROBACION AP1, PLAN PL1, ESTUDIANTE E1
		WHERE E1.CARNET = AS1.CARNET
		AND (	(PL1.ANIO_INICIO = AS1.ANIO AND PL1.CICLO_INICIO <= AS1.CICLO)
				OR (PL1.ANIO_FIN = AS1.ANIO AND PL1.CICLO_FIN >= AS1.CICLO)
				OR (PL1.ANIO_INICIO < AS1.ANIO AND PL1.ANIO_FIN > AS1.ANIO)
		)
		/*AND PL1.ANIO_INICIO <= AS1.ANIO
		AND PL1.ANIO_FIN > AS1.ANIO
		AND PL1.CICLO_INICIO <= AS1.CICLO
		AND PL1.CICLO_FIN > AS1.CICLO*/
		AND PL1.CARRERA = E1.CARRERA
		AND AP1.PLAN = PL1.PLAN
		AND AP1.CARRERA = PL1.CARRERA
		AND AP1.CICLO = AS1.CICLO
		)
	)
;


/*
UPDATE ASIGNACION AS1
	SET AS1.NOTA = AS1.NOTA +(75-NOTA_APROBACION)
	WHERE
	AS1.NOTA < 100 - (75-NOTA_APROBACION)
	AND NOTA_APROBACION = (
		SELECT UNIQUE AP1.NOTA_APROBACION"NOTA_APROBRACION"
		FROM APROBACION AP1, PLAN PL1, ESTUDIANTE E1, ASIGNACION AS2
		WHERE E1.CARNET = AS1.CARNET
		AND PL1.ANIO_INICIO <= AS1.ANIO
		AND PL1.ANIO_FIN > AS1.ANIO
		AND PL1.CICLO_INICIO <= AS1.CICLO
		AND PL1.CICLO_FIN > AS1.CICLO
		AND PL1.CARRERA = E1.CARRERA
		AND AP1.PLAN = PL1.PLAN
		AND AP1.CICLO = AS1.CICLO
	);*/