SELECT CARNET,ANIO,CICLO, MAX(NUM_CURSOS)
FROM(
	SELECT AS1.CARNET"CARNET", AS1.ANIO"ANIO", AS1.CICLO"CICLO", COUNT(AS1.CODIGO) "NUM_CURSOS"
	FROM ASIGNACION AS1
	WHERE NOT EXISTS
	(
		SELECT 1
		FROM CURSO CU1
		WHERE CU1.CURSO = AS1.CODIGO
		AND NOT EXISTS(
			SELECT 1
			FROM ASIGNACION AS2, PLAN PL1, APROBACION AP1, ESTUDIANTE E1
			WHERE AS2.CARNET=AS1.CARNET
			AND (	(PL1.ANIO_INICIO = AS2.ANIO AND PL1.CICLO_INICIO <= AS2.CICLO)
				OR (PL1.ANIO_FIN = AS2.ANIO AND PL1.CICLO_FIN >= AS2.CICLO)
				OR (PL1.ANIO_INICIO < AS2.ANIO AND PL1.ANIO_FIN > AS2.ANIO)
			)
			/*AND PL1.ANIO_INICIO <= AS2.ANIO
			AND PL1.ANIO_FIN > AS2.ANIO
			AND PL1.CICLO_INICIO <= AS2.CICLO
			AND PL1.CICLO_FIN > AS2.CICLO*/
			AND E1.CARNET = AS2.CARNET
			AND PL1.CARRERA = E1.CARRERA
			AND AP1.PLAN = PL1.PLAN
			AND AP1.CARRERA = PL1.CARRERA
			AND AP1.CICLO = AS2.CICLO
			AND AS2.NOTA >= AP1.NOTA_APROBACION
			AND AS2.ZONA >= AP1.ZONA_MINIMA
		)
	)
	AND NOT EXISTS
	(
		SELECT 1
		FROM ASIGNACION AS3
		WHERE
		( 
		AS3.CICLO <> AS1.CICLO
		AND AS3.ANIO = AS1.ANIO
		)
		OR 
		(
		AS3.ANIO <> AS1.ANIO
		AND AS3.CARNET = AS1.CARNET
		AND AS3.CODIGO = AS1.CODIGO
		)		
	)
	AND NOT EXISTS
	(
		SELECT 1
		FROM PRERREQUISITO PR1, ESTUDIANTE E2
		WHERE PR1.CODIGO = AS1.CODIGO
		AND E2.CARNET = AS1.CARNET
		AND PR1.CARRERA = E2.CARRERA
		AND NOT EXISTS(
			SELECT 1
			FROM ASIGNACION AS4, PLAN PL2, APROBACION AP2			
			WHERE AS4.CARNET = AS1.CARNET
			AND AS4.CODIGO = PR1.PRERREQUISITO
			AND (	(PL2.ANIO_INICIO = AS4.ANIO AND PL2.CICLO_INICIO <= AS4.CICLO)
				OR (PL2.ANIO_FIN = AS4.ANIO AND PL2.CICLO_FIN >= AS4.CICLO)
				OR (PL2.ANIO_INICIO < AS4.ANIO AND PL2.ANIO_FIN > AS4.ANIO)
			)
			/*AND PL2.ANIO_INICIO <= AS4.ANIO
			AND PL2.ANIO_FIN > AS4.ANIO
			AND PL2.CICLO_INICIO <= AS4.CICLO
			AND PL2.CICLO_FIN > AS4.CICLO*/
			AND E2.CARNET = AS4.CARNET
			AND PL2.CARRERA = E2.CARRERA
			AND AP2.PLAN = PL2.PLAN
			AND AP2.CARRERA = PL2.CARRERA
			AND AP2.CICLO = AS4.CICLO
			AND AS4.NOTA >= AP2.NOTA_APROBACION
			AND AS4.ZONA >= AP2.ZONA_MINIMA
		)
	)
	GROUP BY AS1.CARNET,AS1.ANIO,AS1.CICLO
)
GROUP BY CARNET,ANIO,CICLO;

/**CONSULTA 26**/
/*
Dar el nombre de los estudiantes que han llevado más cursos en un ciclo, habiéndolos ganado todos y ninguno de los culaes se habia asignado antes, y tenia el prerrequisito aprobado.

Obtenemos el maximo de cursos que un estudiiante se haya asignado tal que no exista algun curso asignado que no exista como curso ganado previamente y nno exista ninguna otra asignacion tque no sea del mismo ciclo que la asignacion anterior y quen o exista algun prerequisito   que no haya aprobado en alguna asignacion.
*/

