/**CONSULTA 28**/
/*
Indicar cuantos estudiantes de cada carrera no han ganando ningun curso.

Obtenemos datos del estudiante y relacionamoes este con el pensum y el plan de tal manera que no exista algun curso tal que no se haya asignado el curso y lo haya perdido.

*/

SELECT E1.CARRERA, COUNT(DISTINCT E1.CARNET)
FROM ESTUDIANTE E1
WHERE EXISTS(
	SELECT *
	FROM PENSUM PE1, PLAN PL1
	WHERE PE1.CARRERA = E1.CARRERA 	
	AND PL1.PLAN = PE1.PLAN
	AND PL1.CARRERA = PE1.CARRERA
	AND NOT EXISTS (
		SELECT 1
		FROM CURSO CU1
		WHERE CU1.CURSO = PE1.CODIGO
		AND NOT EXISTS (
			SELECT 1
			FROM ASIGNACION AS2 ,APROBACION AP1
			WHERE PL1.CARRERA = PE1.CARRERA	
			AND AS2.CARNET = E1.CARNET	
			AND AS2.CODIGO = CU1.CURSO
			AND (	(PL1.ANIO_INICIO = AS2.ANIO AND PL1.CICLO_INICIO <= AS2.CICLO)
				OR (PL1.ANIO_FIN = AS2.ANIO AND PL1.CICLO_FIN >= AS2.CICLO)
				OR (PL1.ANIO_INICIO < AS2.ANIO AND PL1.ANIO_FIN > AS2.ANIO)
			)
			/*AND PL1.ANIO_INICIO <= AS2.ANIO
			AND PL1.ANIO_FIN > AS2.ANIO
			AND PL1.CICLO_INICIO <= AS2.CICLO
			AND PL1.CICLO_FIN > AS2.CICLO*/
			AND AP1.PLAN = PL1.PLAN
			AND AP1.CARRERA = PL1.CARRERA
			AND AP1.CICLO = AS2.CICLO
			AND AS2.ZONA < AP1.ZONA_MINIMA
			AND AS2.NOTA < AP1.NOTA_APROBACION
		)
	)
)
GROUP BY E1.CARRERA;
