/**Vista Count_Rep_Curso_Per_Ciclo

Usada en: Query 25

Devuelve el anio, ciclo, curso y numero de repitentes que ha tenido dicho curso en cualquier anio y ciclo.

*/
CREATE VIEW COUNT_REP_CURSO_PER_CICLO AS (
	SELECT A.ANIO "ANIO", A.CICLO "CICLO", A.CODIGO "CURSO", COUNT(DISTINCT A.CARNET)"COUNT_REP"
	FROM ASIGNACION A, ESTUDIANTE E, APROBACION AP, PLAN PL
	WHERE A.CARNET = E.CARNET
	AND PL.CARRERA = E.CARRERA
	AND (	(PL.ANIO_INICIO = A.ANIO AND PL.CICLO_INICIO <= A.CICLO)
				OR (PL.ANIO_FIN = A.ANIO AND PL.CICLO_FIN >= A.CICLO)
				OR (PL.ANIO_INICIO < A.ANIO AND PL.ANIO_FIN > A.ANIO)
	)
/*	AND PL.ANIO_INICIO <= A.ANIO
	AND PL.ANIO_FIN > A.ANIO
	AND PL.CICLO_INICIO <= A.CICLO
	AND PL.CICLO_FIN > A.CICLO
*/	AND AP.PLAN = PL.PLAN
	AND AP.CARRERA = PL.CARRERA
	AND AP.CICLO = A.CICLO
	AND A.ZONA < AP.ZONA_MINIMA
	AND A.NOTA < AP.NOTA_APROBACION
	GROUP BY A.ANIO , A.CICLO , A.CODIGO
);

/**Vista prom_por_promo_carrera

Usada en: Query 24

Devuelve carnet, promocion (como los primeros 4 digitos del carnet), carrera, promedio de notas
agrupados por promocion y carrera

*/
CREATE VIEW PROM_POR_PROMO_CARRERA AS(
SELECT CARNET,PROMO,CARRERA,AVG(NOTA)"PROMEDIO"
FROM(
	SELECT DISTINCT E.CARNET"CARNET",SUBSTR(E.CARNET,1,4)"PROMO",E.CARRERA"CARRERA",AS2.NOTA"NOTA"
	FROM ESTUDIANTE E, ASIGNACION AS2, PLAN PL1, APROBACION AP1
		WHERE AS2.CARNET = E.CARNET
		AND (	(PL1.ANIO_INICIO = AS2.ANIO AND PL1.CICLO_INICIO <= AS2.CICLO)
				OR (PL1.ANIO_FIN = AS2.ANIO AND PL1.CICLO_FIN >= AS2.CICLO)
				OR (PL1.ANIO_INICIO < AS2.ANIO AND PL1.ANIO_FIN > AS2.ANIO)
			)
		/*AND PL1.ANIO_INICIO <= AS2.ANIO
		AND PL1.ANIO_FIN > AS2.ANIO
		AND PL1.CICLO_INICIO <= AS2.CICLO
		AND PL1.CICLO_FIN > AS2.CICLO*/
		AND PL1.CARRERA = E.CARRERA
		AND AP1.PLAN = PL1.PLAN
		AND AP1.CARRERA = PL1.CARRERA
		AND AP1.CICLO = AS2.CICLO
		AND AS2.NOTA >= AP1.NOTA_APROBACION
		AND AS2.ZONA >= AP1.ZONA_MINIMA
)
GROUP BY CARNET,PROMO,CARRERA
);

/**Vista num_reprob_nrep_per_sec

Usada en: Query 20

Devuelve anio, ciclo, curso, seccion y el numero de reprobados tal que no se hayan asignado este curso previamente( no repitentes)
*/

CREATE VIEW NUM_REPROB_NREP_PER_SEC AS (
	SELECT AS1.ANIO"ANIO", AS1.CICLO"CICLO", AS1.CODIGO"CURSO",AS1.SECCION"SECCION",COUNT(DISTINCT AS1.CARNET)"REPROB"
	FROM ASIGNACION AS1, ESTUDIANTE E1, PLAN PL1, APROBACION AP1
	WHERE E1.CARNET = AS1.CARNET
	AND (	(PL1.ANIO_INICIO = AS1.ANIO AND PL1.CICLO_INICIO <= AS1.CICLO)
				OR (PL1.ANIO_FIN = AS1.ANIO AND PL1.CICLO_FIN >= AS1.CICLO)
				OR (PL1.ANIO_INICIO < AS1.ANIO AND PL1.ANIO_FIN > AS1.ANIO)
	)
	/*AND PL1.ANIO_INICIO <= AS1.ANIO
	AND PL1.ANIO_FIN > AS1.ANIO
	AND PL1.CICLO_INICIO <= AS1.CICLO
	AND PL1.CICLO_FIN > AS1.CICLO*/
	AND PL1.CARRERA = E1.CARRERA
	AND AP1.PLAN = PL1.PLAN
	AND AP1.CARRERA = PL1.CARRERA
	AND AP1.CICLO = AS1.CICLO
	AND AS1.NOTA < AP1.NOTA_APROBACION
	AND AS1.ZONA < AP1.ZONA_MINIMA	
	GROUP BY AS1.ANIO,AS1.CICLO,AS1.CODIGO,AS1.SECCION	
);

/**Vista prom_por_cur_sec_anio_ciclo

Usada en: Query 19

Devuelve curso, seccion anio, ciclo y primedio de notas de la asigancion, agrupado por curso, seccion anio, ciclo
*/

CREATE VIEW PROM_POR_CUR_SEC_ANIO_CICLO AS (
	SELECT AS1.CODIGO"CURSO",AS1.SECCION"SECCION",AS1.ANIO"ANIO",AS1.CICLO"CICLO", AVG(AS1.NOTA)"PROM"
	FROM ASIGNACION AS1	
	GROUP BY AS1.CODIGO,AS1.SECCION,AS1.ANIO,AS1.CICLO	
);

/**Vista ESTUDIANTE_CARR_PROM_EDAD

Usada en: Query 15

Devuelve carrera, carnet, promedio y edad de los estudiantes.
*/
CREATE VIEW ESTUDIANTE_CARR_PROM_EDAD AS(
	SELECT E1.CARRERA"CARRERA", E1.CARNET"CARNET", AVG(AS1.NOTA)"PROM",EXTRACT(YEAR FROM(SYSDATE - E1.FECHA_NACIMIENTO) YEAR TO MONTH)"EDAD"
	FROM ESTUDIANTE E1, CARRERA C1, ASIGNACION AS1,APROBACION AP1, PLAN PL1
	WHERE E1.CARNET = AS1.CARNET AND E1.CARRERA = C1.CARRERA	
	AND PL1.CARRERA = E1.CARRERA
	AND (	(PL1.ANIO_INICIO = AS1.ANIO AND PL1.CICLO_INICIO <= AS1.CICLO)
				OR (PL1.ANIO_FIN = AS1.ANIO AND PL1.CICLO_FIN >= AS1.CICLO)
				OR (PL1.ANIO_INICIO < AS1.ANIO AND PL1.ANIO_FIN > AS1.ANIO)
	)
	/*AND PL1.ANIO_INICIO <= AS1.ANIO
	AND PL1.ANIO_FIN > AS1.ANIO
	AND PL1.CICLO_INICIO <= AS1.CICLO
	AND PL1.CICLO_FIN > AS1.CICLO*/
	AND PL1.CARRERA = E1.CARRERA
	AND AP1.PLAN = PL1.PLAN
	AND AP1.CARRERA = PL1.CARRERA
	AND AP1.CICLO = AS1.CICLO
	AND AS1.NOTA >= AP1.NOTA_APROBACION
	AND AS1.ZONA >= AP1.ZONA_MINIMA	
	GROUP BY E1.CARRERA,E1.CARNET,E1.FECHA_NACIMIENTO
); 

/**Vista LISTADO_ESTUDIANTES_CIERRE

Usada en: Query 27,14

Devuelve los estudiantes que han cerrado alguna carrera*/

create view listado_estudiantes_cierre as(
	SELECT ES1.CARNET"CARNET", (MAX(AS0.ANIO)-MIN(AS0.ANIO))"DELTAT",ES1.CARRERA"CARRERA"
	FROM ESTUDIANTE ES1, CARRERA CA1, ASIGNACION AS0
	WHERE CA1.CARRERA = ES1.CARRERA AND AS0.CARNET = ES1.CARNET
	AND EXISTS( /**OBLIGATORIEDAD*/
		SELECT 1
		FROM PENSUM PE1, PLAN PL1
		WHERE PE1.CARRERA = CA1.CARRERA 
		AND PL1.CARRERA = CA1.CARRERA 
		AND PE1.PLAN = PL1.PLAN
		AND PE1.OBLIGATORIO = 1
		AND NOT EXISTS(
			SELECT 1
			FROM CURSO CU1
			WHERE PE1.CODIGO = CU1.CURSO
			AND NOT EXISTS(
				SELECT 1
				FROM ASIGNACION AS1, APROBACION AP1
				WHERE AS1.CARNET = ES1.CARNET
				AND AS1.CODIGO = CU1.CURSO
				AND (	(PL1.ANIO_INICIO = AS1.ANIO AND PL1.CICLO_INICIO <= AS1.CICLO)
					OR (PL1.ANIO_FIN = AS1.ANIO AND PL1.CICLO_FIN >= AS1.CICLO)
					OR (PL1.ANIO_INICIO < AS1.ANIO AND PL1.ANIO_FIN > AS1.ANIO)
				)
				/*AND PL1.ANIO_INICIO <= AS1.ANIO
				AND PL1.ANIO_FIN > AS1.ANIO
				AND PL1.CICLO_INICIO <= AS1.CICLO
				AND PL1.CICLO_FIN > AS1.CICLO*/
				AND AP1.PLAN = PL1.PLAN
				AND AP1.CARRERA = PL1.CARRERA
				AND AP1.CICLO = AS1.CICLO
				AND AS1.NOTA >= AP1.NOTA_APROBACION
				AND AS1.ZONA >= AP1.ZONA_MINIMA	
			)
		)
	)
	AND EXISTS( /**CONTEO CREDITOS*/
		SELECT 1
		FROM PENSUM PE1, PLAN PL1
		WHERE PE1.CARRERA = CA1.CARRERA
		AND PL1.PLAN = PE1.PLAN
		AND PL1.CARRERA = PE1.CARRERA
		AND EXISTS(
			SELECT 1
			FROM ASIGNACION AS1, APROBACION AP1, CURSO CU1			
			WHERE AS1.CARNET = ES1.CARNET
			AND AS1.CODIGO = CU1.CURSO
			AND (	(PL1.ANIO_INICIO = AS1.ANIO AND PL1.CICLO_INICIO <= AS1.CICLO)
				OR (PL1.ANIO_FIN = AS1.ANIO AND PL1.CICLO_FIN >= AS1.CICLO)
				OR (PL1.ANIO_INICIO < AS1.ANIO AND PL1.ANIO_FIN > AS1.ANIO)
			)
			/*AND PL1.ANIO_INICIO <= AS1.ANIO
			AND PL1.ANIO_FIN > AS1.ANIO
			AND PL1.CICLO_INICIO <= AS1.CICLO
			AND PL1.CICLO_FIN > AS1.CICLO*/
			AND AP1.PLAN = PL1.PLAN
			AND AP1.CARRERA = PL1.CARRERA
			AND AP1.CICLO = AS1.CICLO
			AND AS1.NOTA >= AP1.NOTA_APROBACION
			AND AS1.ZONA >= AP1.ZONA_MINIMA	
			GROUP BY AS1.CARNET
			HAVING SUM(CU1.CREDITOS) >= CA1.CREDITOS_CIERRE
		)
	)
	GROUP BY ES1.CARRERA,ES1.CARNET
);

/**Vista REPROBADOS_POR_CAT_CAR

Usada en: Query 07

Devuelve un promedio de estudiantes reprobados por catedratico y carrera*/
CREATE VIEW REPROBADOS_POR_CAT_CAR AS (
	SELECT CAR.CARRERA"CARR", CAT.CATEDRATICO"CAT",AS1.CODIGO,COUNT(DISTINCT EST.CARNET)"NUM_REPROBADOS"
	FROM CATEDRATICO CAT, CARRERA CAR, ASIGNACION AS1, SECCION SEC, ESTUDIANTE EST, PLAN PL1, APROBACION AP1
	WHERE SEC.CATEDRATICO = CAT.CATEDRATICO
	AND SEC.ANIO = AS1.ANIO
	AND SEC.CICLO = AS1.CICLO
	AND SEC.CODIGO = AS1.CODIGO
	AND SEC.SECCION = AS1.SECCION
	AND EST.CARNET = AS1.CARNET
	AND EST.CARRERA = CAR.CARRERA
	AND PL1.CARRERA = EST.CARRERA
	AND ((PL1.ANIO_INICIO = AS1.ANIO AND PL1.CICLO_INICIO <= AS1.CICLO)
		OR (PL1.ANIO_FIN = AS1.ANIO AND PL1.CICLO_FIN >= AS1.CICLO)
		OR (PL1.ANIO_INICIO < AS1.ANIO AND PL1.ANIO_FIN > AS1.ANIO)
	)
/*	AND PL1.ANIO_INICIO <= AS1.ANIO
	AND PL1.ANIO_FIN > AS1.ANIO
	AND PL1.CICLO_INICIO <= AS1.CICLO
	AND PL1.CICLO_FIN > AS1.CICLO*/
	AND AP1.CICLO = AS1.CICLO
	AND AP1.PLAN = PL1.PLAN
	AND AP1.CARRERA = PL1.CARRERA
	AND (AS1.ZONA <= AP1.ZONA_MINIMA
	OR AS1.NOTA <= AP1.NOTA_APROBACION
	)
	GROUP BY CAR.CARRERA,CAT.CATEDRATICO,AS1.CODIGO
);