######################################################################
# Automatically generated by qmake (1.07a) Sun Nov 11 22:41:28 2007
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += prodcon.h
SOURCES += prodcon.cpp
