/*
 * OpcionesJugador.java
 *
 * Created on 12 de septiembre de 2005, 07:23 PM
 */

import javax.swing.*;
/**Clase que define las opcines del jugador en un dialogo
 * @author  Erik Giron*/
public class OpcionesJugador extends javax.swing.JPanel {
    private Jugador j, j2; /**Objeto Jugador a asignar propiedades*/
    private String nombre ="Jugador 1", nombre2 = "Jugador 2";
    private int color=0,pos=0,color2=1,pos2=1; /**Enteros de transicion*/
    private boolean setted = false;/**Bandera para ver si ha sido configurado el jugador*/
    //private JLabel aviso;
    /** Crea nuevo form de OpcionesJugador */
    public OpcionesJugador() {
        initComponents();
        this.setVisible(true);
        //aviso = new JLabel("");
        aviso.setText("");
        //jPanel1.add(aviso);

    }
    /**Devuelve jugador Configurado
     * @return Instancia de Jugador configurado*/
    public Jugador getJugador(){
        return j;
    }

    /**Devuelve jugador Configurado
     * @return Instancia de Jugador configurado*/
    public Jugador getJugador2(){
        return j2;
    }

    /**@return Devuelve estado booleano si se ha configurado el jugador */
    public boolean getStatus(){
        return setted;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanelNombre = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jPanelColorRoot = new javax.swing.JPanel();
        jLabelColor = new javax.swing.JLabel();
        jComboBoxColor = new javax.swing.JComboBox();
        jPanelPos = new javax.swing.JPanel();
        jLabelPos = new javax.swing.JLabel();
        jComboBoxPos = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jPanelNombre1 = new javax.swing.JPanel();
        jLabelNombre2 = new javax.swing.JLabel();
        jTextFieldNombre2 = new javax.swing.JTextField();
        jPanelColorRoot2 = new javax.swing.JPanel();
        jLabelColor2 = new javax.swing.JLabel();
        jComboBoxColor2 = new javax.swing.JComboBox();
        jPanelPos2 = new javax.swing.JPanel();
        jLabelPos2 = new javax.swing.JLabel();
        jComboBoxPos2 = new javax.swing.JComboBox();
        jPanelAplicar = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        aviso = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.TitledBorder(null, "Opciones de Jugador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 0, 0)));
        jPanel2.setLayout(new java.awt.GridLayout(5, 0));

        jPanel2.setBorder(new javax.swing.border.TitledBorder("Jugador 1"));
        jPanel2.setMinimumSize(new java.awt.Dimension(207, 194));
        jPanel2.setPreferredSize(new java.awt.Dimension(256, 194));
        jLabelNombre.setText("Nombre:");
        jPanelNombre.add(jLabelNombre);

        jTextFieldNombre.setText("Jugador 1");
        jTextFieldNombre.setToolTipText("Ingresar nombre Jugador 1");
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jPanelNombre.add(jTextFieldNombre);

        jPanel2.add(jPanelNombre);

        jLabelColor.setText("Color de Fichas");
        jPanelColorRoot.add(jLabelColor);

        jComboBoxColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rojo", "Azul", "Verde", "Negro" }));
        jComboBoxColor.setToolTipText("Ingresar Color de Fichas Jugador 1");
        jComboBoxColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxColorActionPerformed(evt);
            }
        });

        jPanelColorRoot.add(jComboBoxColor);

        jPanel2.add(jPanelColorRoot);

        jLabelPos.setText("Posicion Inicial:");
        jPanelPos.add(jLabelPos);

        jComboBoxPos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arriba", "Abajo", "Izquierda", "Derecha" }));
        jComboBoxPos.setToolTipText("Ingresar posicion dentro del tablero...");
        jComboBoxPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPosActionPerformed(evt);
            }
        });

        jPanelPos.add(jComboBoxPos);

        jPanel2.add(jPanelPos);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(5, 0));

        jPanel3.setBorder(new javax.swing.border.TitledBorder("Jugador 2"));
        jPanel3.setMinimumSize(new java.awt.Dimension(207, 194));
        jPanel3.setPreferredSize(new java.awt.Dimension(256, 194));
        jLabelNombre2.setText("Nombre:");
        jPanelNombre1.add(jLabelNombre2);

        jTextFieldNombre2.setText("Jugador 2");
        jTextFieldNombre2.setToolTipText("Ingresar nombre Jugador 2");
        jPanelNombre1.add(jTextFieldNombre2);

        jPanel3.add(jPanelNombre1);

        jLabelColor2.setText("Color de Fichas:");
        jPanelColorRoot2.add(jLabelColor2);

        jComboBoxColor2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rojo", "Azul", "Verde", "Negro" }));
        jComboBoxColor2.setSelectedIndex(1);
        jComboBoxColor2.setToolTipText("Ingresar Color de Fichas Jugador 2");
        jComboBoxColor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxColor2ActionPerformed(evt);
            }
        });

        jPanelColorRoot2.add(jComboBoxColor2);

        jPanel3.add(jPanelColorRoot2);

        jLabelPos2.setText("Posicion Inicial:");
        jPanelPos2.add(jLabelPos2);

        jComboBoxPos2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arriba", "Abajo", "Izquierda", "Derecha" }));
        jComboBoxPos2.setSelectedIndex(1);
        jComboBoxPos2.setToolTipText("Ingresar posicion dentro del tablero...");
        jComboBoxPos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPos2ActionPerformed(evt);
            }
        });

        jPanelPos2.add(jComboBoxPos2);

        jPanel3.add(jPanelPos2);

        jPanel1.add(jPanel3);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Aplicar");
        jButton1.setToolTipText("Guardar Cambios");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });

        jPanelAplicar.add(jButton1);

        add(jPanelAplicar, java.awt.BorderLayout.SOUTH);

        aviso.setForeground(new java.awt.Color(255, 102, 102));
        aviso.setText("jLabel1");
        add(aviso, java.awt.BorderLayout.NORTH);

    }
    // </editor-fold>//GEN-END:initComponents

    private void jComboBoxPos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPos2ActionPerformed
        this.pos2 = jComboBoxPos2.getSelectedIndex();
    }//GEN-LAST:event_jComboBoxPos2ActionPerformed

    private void jComboBoxColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxColor2ActionPerformed
        this.color2 = jComboBoxColor2.getSelectedIndex();
    }//GEN-LAST:event_jComboBoxColor2ActionPerformed

    private void jComboBoxPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPosActionPerformed
        this.pos = jComboBoxPos.getSelectedIndex();
    }//GEN-LAST:event_jComboBoxPosActionPerformed
    // Accion para evento de Combo Box
    private void jComboBoxColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxColorActionPerformed
        this.color = jComboBoxColor.getSelectedIndex();
    }//GEN-LAST:event_jComboBoxColorActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        //j.setNombre();
        // Establece propiedades para jugador
        this.nombre = jTextFieldNombre.getText();
        this.nombre2 = jTextFieldNombre2.getText();

        //this.color = jComboBoxColor.getSelectedIndex();
        //this.pos = jComboBoxPos.getSelectedIndex();
        if ((this.nombre.length() > 0) && (this.nombre2.length() > 0) && (this.nombre.equalsIgnoreCase(this.nombre2)==false)){
            if((this.pos != this.pos2) && (this.color != this.color2)){
                j = new Jugador();
                j.setJugador(this.nombre,this.pos,this.color);
                j2 = new Jugador();
                j2.setJugador(this.nombre2,this.pos2,this.color2);
                this.setted = true;
                this.setVisible(false);
            }
            else
            {
                aviso.setText("AVISO: Los jugadores no pueden contener parametros iguales");
            }
        }
        else{
            aviso.setText("AVISO: Debe agregarles un nombre diferente a cada jugador");
        }
            //jPanel1.add(new JLabel("Ingrese un nombre por favor"), java.awt.BorderLayout.SOUTH);

    }//GEN-LAST:event_jButton1MouseReleased

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed

    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aviso;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxColor;
    private javax.swing.JComboBox jComboBoxColor2;
    private javax.swing.JComboBox jComboBoxPos;
    private javax.swing.JComboBox jComboBoxPos2;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelColor2;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre2;
    private javax.swing.JLabel jLabelPos;
    private javax.swing.JLabel jLabelPos2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAplicar;
    private javax.swing.JPanel jPanelColorRoot;
    private javax.swing.JPanel jPanelColorRoot2;
    private javax.swing.JPanel jPanelNombre;
    private javax.swing.JPanel jPanelNombre1;
    private javax.swing.JPanel jPanelPos;
    private javax.swing.JPanel jPanelPos2;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombre2;
    // End of variables declaration//GEN-END:variables

}
