/*
 * VisorCodigo.java
 *
 * Created on 25 de septiembre de 2005, 11:06 AM
 */

/**
 *
 *
 */
import java.io.*;
import java.applet.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.util.*;
import java.net.*;
/**Panel que representa el Visor de Codigo fuente,
 * NOTA: el path es relativo al documento html
 * @author  Erik Giron*/
public class VisorCodigo extends javax.swing.JPanel {
    //Arreglo de los nombres de los codigos fuentes
    private static String[] nomArchivos = {"Console.java","Ficha.java",
            "Jugador.java","MainPanel.java","OpcionesJugador.java",
            "OtelloApplet.java","VisorCodigo.java","Tablero.java","Circulo.java"};

    private final String path = "./src/"; // path del directorio donde estan las fuentes respecto el documento HTML
    private String filename;
    private File arch;
    private JApplet principal; //Referencia al applet principal

    /** Crea nueva forma VisorCodigo */
    public VisorCodigo() {
        initComponents();
        setIndicesSeleccion();
    }
    public VisorCodigo(JApplet app) {
        //initComponents();
        //setIndicesSeleccion();
        this();
        setAppletPrincipal(app);
    }
    /**Establece los elementos de la lista del ComboBox desde el arreglo de strings*/
    public void setIndicesSeleccion(){
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel());
        int i = 0;
        try{
            while(nomArchivos[i] != null){
                jComboBox1.insertItemAt(nomArchivos[i], i);
                i++;
            }
        }
        catch( Exception e)
        { System.out.println(e.toString());}
        jComboBox1.setSelectedIndex(0);

    }

    /**Asigna Applet principal para obtener el CodeBase
     *@param applet Applet que sera la raiz de la aplicacion*/
    public void setAppletPrincipal(JApplet applet){
        principal = applet;
    }

    /**Escribe texto en el JEditorPane
     * @param seleccion Nombre del archivo que se abrira, devuelto por el evento de ComboBox*/
    public void escribirTexto(String seleccion){
        //arch = new File("/home/kreig/fp.cfg");
        //arch = new File(path + nomArchivos[1]);
        filename = path + seleccion;
        InputStream is;
	InputStreamReader isr;
        URL url;
        try{
            url = new URL(principal.getDocumentBase(),filename);
            //url = new URL(principal.getDocumentBase(),"../src/" + seleccion);
            is = url.openStream();
	    isr = new InputStreamReader(is);
            BufferedReader in = new BufferedReader(isr);
            jEditorPane1.read(in,url);
            //1/BufferedReader in = new BufferedReader(new FileReader(arch));
//            BufferedReader in = new BufferedReader(new FileReader(filename));

            //jEditorPane1.read(in,new FileReader(filename));
        }
        catch(IOException e){
            System.out.println(e.toString());
        }
        catch(Exception e){
            System.out.println(e.toString());
        }

        //jEditorPane1.
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Archivo a ver:");
        jPanel2.add(jLabel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ficha.java", "s.f" }));
        jComboBox1.setToolTipText("Seleccione aqui el archivo fuente que desee visualizar.");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel2.add(jComboBox1);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jEditorPane1.setFont(new java.awt.Font("Monospaced", 0, 12));
        jScrollPane1.setViewportView(jEditorPane1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        escribirTexto(jComboBox1.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
