/*
 * AbstractQueue.java
 *
 * Created on August 17, 2007, 5:59 PM
 */

package pcb;
import java.util.*;
import javax.swing.*;

/**
 * Cola abstracta de procesos
 * @author  Erik giron
 */
public abstract class AbstractQueue extends javax.swing.JPanel implements Runnable{
    
    protected java.util.LinkedList<Pcb> procesos = new LinkedList<Pcb>();
    protected boolean changed = false;
    
    protected JLabel[] labels = new JLabel[15];
    
    protected int actual = 0;
    //protected ArrayList labelList = new ArrayList();
            
    
    /** Creates new form AbstractQueue */
    public AbstractQueue() {
        initComponents();
        this.setBounds(12,16,215,312);        
        
        for (int i = 0; i < 15; i++){
            labels[i] = new JLabel("");
            this.add(labels[i]);
        }
    }
    
    public abstract void Push(Pcb p);    
    
    public abstract Pcb Pop();
    
    public void run(){
        Iterator i = procesos.iterator();
        while(true && Thread.currentThread().isAlive()){
            
                rotate();                
                if (changed){
                    changed = false;
                    /*
                    this.removeAll();
                    while(i.hasNext()){
                        this.add((JPanel)i.next());
                    }*/
                }
            
        }
    }

    public LinkedList<Pcb> getProcesos() {
        return procesos;
    }
    
    
    public abstract void rotate();
    
    
        
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(15, 0));

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
