/*
 * MainWindow.java
 *
 * Created on August 19, 2007, 4:07 PM
 */

package pcb;

/**
 *
 * @author  kreig
 */
public class MainWindow extends javax.swing.JFrame implements Runnable{
    private boolean exec = false;
    WaitQueue waitq = new WaitQueue();
    Thread w;
    Thread currThread;
    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
        this.jPanelWait.add(waitq);
        this.jLabelRun.setText("Nada");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        Opciones = new javax.swing.ButtonGroup();
        jPanelProcesses = new javax.swing.JPanel();
        jPanelWait = new javax.swing.JPanel();
        jPanelRun = new javax.swing.JPanel();
        jLabelRun = new javax.swing.JLabel();
        jPanelControl = new javax.swing.JPanel();
        jRadioButtonMan = new javax.swing.JRadioButton();
        jButtonExec = new javax.swing.JButton();
        jRadioButtonAuto = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldQuantum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButtonGetSystem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PCB, por Erik Giron (200313492)");
        jPanelProcesses.setBorder(javax.swing.BorderFactory.createTitledBorder("Procesos"));
        jPanelWait.setBorder(javax.swing.BorderFactory.createTitledBorder("Espera"));
        javax.swing.GroupLayout jPanelWaitLayout = new javax.swing.GroupLayout(jPanelWait);
        jPanelWait.setLayout(jPanelWaitLayout);
        jPanelWaitLayout.setHorizontalGroup(
            jPanelWaitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );
        jPanelWaitLayout.setVerticalGroup(
            jPanelWaitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jPanelRun.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejecucion"));
        jLabelRun.setText("jLabel4");

        javax.swing.GroupLayout jPanelRunLayout = new javax.swing.GroupLayout(jPanelRun);
        jPanelRun.setLayout(jPanelRunLayout);
        jPanelRunLayout.setHorizontalGroup(
            jPanelRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRunLayout.createSequentialGroup()
                .addComponent(jLabelRun)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanelRunLayout.setVerticalGroup(
            jPanelRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRunLayout.createSequentialGroup()
                .addComponent(jLabelRun)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelProcessesLayout = new javax.swing.GroupLayout(jPanelProcesses);
        jPanelProcesses.setLayout(jPanelProcessesLayout);
        jPanelProcessesLayout.setHorizontalGroup(
            jPanelProcessesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProcessesLayout.createSequentialGroup()
                .addComponent(jPanelWait, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelProcessesLayout.setVerticalGroup(
            jPanelProcessesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWait, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelRun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelControl.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        Opciones.add(jRadioButtonMan);
        jRadioButtonMan.setText("Manual");
        jRadioButtonMan.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonMan.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButtonMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonManActionPerformed(evt);
            }
        });

        jButtonExec.setText("Ejecutar");
        jButtonExec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecActionPerformed(evt);
            }
        });

        Opciones.add(jRadioButtonAuto);
        jRadioButtonAuto.setText("Automatico");
        jRadioButtonAuto.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonAuto.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButtonAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAutoActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Nombre");

        jLabel3.setText("Quantum");

        jButtonAdd.setText("Agregar");
        jButtonAdd.setEnabled(false);
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldQuantum, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addComponent(jButtonAdd)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)))
        );

        jButtonGetSystem.setText("Obtener del Sistema");
        jButtonGetSystem.setEnabled(false);
        jButtonGetSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetSystemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelControlLayout = new javax.swing.GroupLayout(jPanelControl);
        jPanelControl.setLayout(jPanelControlLayout);
        jPanelControlLayout.setHorizontalGroup(
            jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlLayout.createSequentialGroup()
                .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButtonMan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelControlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButtonAuto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGetSystem))
                    .addGroup(jPanelControlLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButtonExec)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanelControlLayout.setVerticalGroup(
            jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlLayout.createSequentialGroup()
                .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonMan)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGetSystem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExec)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelProcesses, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelControl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelProcesses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        if(this.jTextFieldId.getText().length() != 0
                && this.jTextFieldName.getText().length() != 0
                && this.jTextFieldQuantum.getText().length() != 0){
                //Process p = new Process(Integer.parseInt(this.jTextFieldId.getText()),this.jTextFieldName.getText(),Float.parseFloat(this.jTextFieldQuantum.getText()),Math.random() * 1000);
                Pcb pr = new Pcb();
                pr.setId(Integer.parseInt(this.jTextFieldId.getText()));
                pr.setName(this.jTextFieldName.getText());
                pr.setQuantum(Float.parseFloat(this.jTextFieldQuantum.getText()));
                pr.setSize((float)Math.random() * 1000);
                //Process p = new Process();
                //p.setProceso(pr);
                waitq.Push(pr);
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonGetSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetSystemActionPerformed
        getSystemProcesses();
    }//GEN-LAST:event_jButtonGetSystemActionPerformed

    private void jRadioButtonAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAutoActionPerformed
        jButtonAdd.setEnabled(false);
        jButtonGetSystem.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonAutoActionPerformed

    private void jButtonExecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecActionPerformed
        if(exec){
            jButtonExec.setText("Ejecutar");
            jButtonAdd.setEnabled(true);
            jButtonGetSystem.setEnabled(true);            
            this.jRadioButtonAuto.setEnabled(true);
            this.jRadioButtonMan.setEnabled(true);
            exec = false;
            stopprocs();
        }
        else{
            jButtonExec.setText("Detener");
            jButtonAdd.setEnabled(false);            
            jButtonGetSystem.setEnabled(false);
            this.jRadioButtonAuto.setEnabled(false);
            this.jRadioButtonMan.setEnabled(false);
            exec = true;
            startprocs();
        }
            
        
    }//GEN-LAST:event_jButtonExecActionPerformed

    private void jRadioButtonManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonManActionPerformed
        jButtonAdd.setEnabled(true);
        jButtonGetSystem.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonManActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    /*Obtiene los procesos del sistema*/
    private void getSystemProcesses() {
        java.lang.Process ps;
        String sret;
        byte []ret = new byte[10*15];
        int t = 5;        
        //Usar ps -eo fname
        try{
            ps = java.lang.Runtime.getRuntime().exec("ps -eo fname");
            //ret = ps.getInputStream().;
            ps.waitFor();
            //System.in.read(ret);
            ps.getInputStream().read(ret);            
            sret = new String(ret);
            t = 1 + t;
        }
        catch(Exception e){
            
        }
        finally{
            
        }
        
        //throw new UnsupportedOperationException("Not yet implemented");
    }

    private void startprocs() {  
        w = new Thread((Runnable)waitq);
        currThread = new Thread(this);
        w.start();     
        currThread.start();
    }

    private void stopprocs() {
        w.yield();
        currThread.yield();
    }

    public void run() {
        Pcb tmp;
        while(waitq.getProcesos().size() > 0 && exec){
            try{
                //w.wait();
                tmp = waitq.Pop();
                jLabelRun.setText(tmp.getId() + " " + tmp.getName() + " " + tmp.getQuantum());
                //w.notify();
                //w.sleep((int)tmp.getQuantum() * 1000);
                currThread.sleep((int)tmp.getQuantum() * 1000);
                waitq.Push(tmp);
                //w.notify();
            }
            catch(InterruptedException e){
                
            }
//            finally{
//                this.repaint();
//           }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Opciones;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonExec;
    private javax.swing.JButton jButtonGetSystem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private static javax.swing.JLabel jLabelRun;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelControl;
    private javax.swing.JPanel jPanelProcesses;
    private javax.swing.JPanel jPanelRun;
    private javax.swing.JPanel jPanelWait;
    private javax.swing.JRadioButton jRadioButtonAuto;
    private javax.swing.JRadioButton jRadioButtonMan;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldQuantum;
    // End of variables declaration//GEN-END:variables
    
}
