/*
 * Process.java
 *
 * Created on August 17, 2007, 5:36 PM
 */

package pcb;

import javax.swing.*;
/**
 * Panel que representa un proceso, contiene estructura de PCB
 * @author  Erik Giron
 */
public class Process extends javax.swing.JPanel implements Runnable {
    
    private Pcb proceso; /*Proceso actual en ejecucion*/    
    
    /** Creates new form Process */
    public Process() {
        initComponents();        
        this.setBounds(0,0,232,15);
        proceso = new Pcb("proceso");
    }

    public Process(int pid, String name, float quantum) {
        super();
        proceso.setId(pid);
        proceso.setName(name);
        proceso.setQuantum(quantum);
        this.jLabelName.setText(proceso.getName());
        this.jLabelSize.setText(Float.toString(proceso.getSize()));
        this.jLabelPID.setText(Integer.toString(proceso.getId()));
    }
    
    
    public Process(int pid, String name,float quantum, float size) {
        super();
        proceso.setId(pid);
        proceso.setName(name);
        proceso.setQuantum(quantum);
        proceso.setSize(size);
        this.jLabelName.setText(proceso.getName());
        this.jLabelSize.setText(Float.toString(proceso.getSize()));
        this.jLabelPID.setText(Integer.toString(proceso.getId()));
    }
    
    public void run(){
        while(true){            
            this.repaint();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabelName = new javax.swing.JLabel();
        jLabelPID = new javax.swing.JLabel();
        jLabelSize = new javax.swing.JLabel();

        jLabelName.setForeground(new java.awt.Color(0, 0, 255));
        jLabelName.setText("Name");

        jLabelPID.setForeground(new java.awt.Color(255, 51, 51));
        jLabelPID.setText("PID");

        jLabelSize.setText("Size");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelPID)
                .addGap(76, 76, 76)
                .addComponent(jLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jLabelSize))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelPID)
                .addComponent(jLabelSize)
                .addComponent(jLabelName))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPID;
    private javax.swing.JLabel jLabelSize;
    // End of variables declaration//GEN-END:variables
    

    public Pcb getProceso() {
        return proceso;
    }
    

    public void setProceso(Pcb proceso) {
        this.proceso = proceso;
    }
}
