
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Mar 19 14:38:11 CST 2007
//----------------------------------------------------

package lalrgen;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_APARPUN = 5;
  public static final int TK_CPARPUN = 6;
  public static final int TK_COMA = 10;
  public static final int KW_TERM = 7;
  public static final int TK_ID = 14;
  public static final int EOF = 0;
  public static final int TK_PUNCOMA = 9;
  public static final int TK_SEPARATOR = 2;
  public static final int error = 1;
  public static final int STR_SENTENCIAS = 15;
  public static final int KW_INT = 11;
  public static final int KW_REAL = 12;
  public static final int KW_NO = 8;
  public static final int TK_DOSPUNTOS = 4;
  public static final int KW_STR = 13;
  public static final int TK_PRODUCE = 3;
}

